services:
  app:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/website
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./.env.dev

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=blog
      - POSTGRES_DB=blog 
      - POSTGRES_PASSWORD=sky
    
volumes:
  postgres_data:
