services:
  app:
    container_name: django
    build: .
    command:  gunicorn website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/website
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment: 
#       - POSTGRES_USER=blog
#       - POSTGRES_DB=blog 
#       - POSTGRES_PASSWORD=sky
    
  nginx:
    build: ./nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443         
    depends_on:
      - app


# volumes:
#   postgres_data:
