# Generated by Django 5.0.4 on 2024-04-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorinfo',
            name='author_role',
            field=models.CharField(default='emty', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authorinfo',
            name='author_resume',
            field=models.TextField(),
        ),
    ]
