# Generated by Django 5.0.4 on 2024-04-07 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_authorinfo_author_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masters_study', models.CharField(max_length=100)),
                ('masters_university', models.CharField(max_length=100)),
                ('masters_graduation_date', models.DateField()),
                ('bachelor_study', models.CharField(max_length=100)),
                ('bachelor_university', models.CharField(max_length=100)),
                ('bachelor_graduation_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='pages.authorinfo')),
            ],
        ),
    ]
