# Generated by Django 5.0.4 on 2024-04-07 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_authorstudies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_image', models.ImageField(upload_to='images/')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pages.expertisecategory')),
            ],
        ),
    ]
