# Generated by Django 5.0.4 on 2024-04-07 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_expertisecategory_expertisetool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertisetool',
            name='tool_image',
            field=models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png', 'jpg'])]),
        ),
    ]
