# Generated by Django 5.0.4 on 2024-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_expertisetool_tool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertisetool',
            name='tool_url',
            field=models.URLField(default='empty'),
            preserve_default=False,
        ),
    ]
