# Generated by Django 5.0.4 on 2024-04-07 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_authorinfo_author_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertisecategory',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='pages.authorinfo'),
        ),
    ]
