# Generated by Django 5.0.4 on 2024-04-07 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_workexperience_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='pages.authorinfo'),
        ),
    ]
