# Generated by Django 5.0.4 on 2024-04-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_workexperience_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='position',
            field=models.CharField(default='empty', max_length=250),
            preserve_default=False,
        ),
    ]
