# Generated by Django 5.0.4 on 2024-04-08 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_academicparticipation_project_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicparticipation',
            name='year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='year',
        ),
        migrations.AlterField(
            model_name='academicparticipation',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_participations', to='pages.authorinfo'),
        ),
        migrations.AlterField(
            model_name='authorstudies',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='pages.authorinfo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pages.authorinfo'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='pages.authorinfo'),
        ),
    ]
