# Generated by Django 5.0.4 on 2024-04-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_academicparticipation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicparticipation',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default='2002'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
