# Generated by Django 5.0.4 on 2024-04-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_academicparticipation_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicparticipation',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(),
        ),
    ]
