# Generated by Django 5.0.4 on 2024-04-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_academicparticipation_year_alter_project_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicparticipation',
            name='year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='year',
        ),
    ]
