# Generated by Django 5.0.4 on 2024-04-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_academicparticipation_year_project_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='role',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
