# Generated by Django 5.0.4 on 2024-04-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_academicparticipation_year_alter_project_year_and_more'),
        ('pages', '0018_publication_role'),
    ]

    operations = [
    ]
