# Generated by Django 5.0.4 on 2024-04-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_merge_20240408_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicParticipation',
        ),
    ]
