# Generated by Django 5.0.4 on 2024-04-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_test_delete_academicparticipation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('event', models.TextField()),
                ('skills', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_participations', to='pages.authorinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
