# Generated by Django 5.0.4 on 2024-04-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_test_remove_publication_author_delete_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pages.authorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('participants', models.CharField(max_length=250)),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                ('journal', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='pages.authorinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
