# Generated by Django 5.0.3 on 2024-03-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('df', 'draft'), ('pb', 'published')], default='df', max_length=2),
        ),
    ]
