# Generated by Django 4.1 on 2024-03-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
