# Generated by Django 4.1 on 2024-04-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_posted_post_updated_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted',
            new_name='publish',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
    ]
